// constants/country.js
export const COUNTRY = {
    AE: "United Arab Emirates",
    AR: "Argentina",
    AT: "Austria",
    AU: "Australia",
    BD: "Bangladesh",
    BE: "Belgium",
    BG: "Bulgaria",
    BH: "Bahrain",
    BN: "Brunei",
    BR: "Brazil",
    BT: "Bhutan",
    CA: "Canada",
    CH: "Switzerland",
    CL: "Chile",
    CN: "China",
    CO: "Colombia",
    CZ: "Czech Republic",
    DE: "Germany",
    DK: "Denmark",
    DZ: "Algeria",
    EG: "Egypt",
    ES: "Spain",
    FI: "Finland",
    FJ: "Fiji",
    FR: "France",
    GR: "Greece",
    HK: "Hong Kong",
    HR: "Croatia",
    HU: "Hungary",
    ID: "Indonesia",
    IE: "Ireland",
    IL: "Israel",
    IN: "India",
    IS: "Iceland",
    IT: "Italy",
    JO: "Jordan",
    JP: "Japan",
    KE: "Kenya",
    KH: "Cambodia",
    KR: "South Korea",
    KW: "Kuwait",
    LA: "Laos",
    LB: "Lebanon",
    LK: "Sri Lanka",
    MA: "Morocco",
    MM: "Myanmar",
    MN: "Mongolia",
    MO: "Macau",
    MV: "Maldives",
    MX: "Mexico",
    MY: "Malaysia",
    NG: "Nigeria",
    NL: "Netherlands",
    NO: "Norway",
    NP: "Nepal",
    NZ: "New Zealand",
    OM: "Oman",
    PE: "Peru",
    PG: "Papua New Guinea",
    PH: "Philippines",
    PK: "Pakistan",
    PL: "Poland",
    PT: "Portugal",
    QA: "Qatar",
    RO: "Romania",
    RU: "Russia",
    SA: "Saudi Arabia",
    SE: "Sweden",
    SG: "Singapore",
    TH: "Thailand",
    TL: "Timor-Leste",
    TN: "Tunisia",
    TR: "Turkey",
    TW: "Taiwan",
    UA: "Ukraine",
    UK: "United Kingdom",
    US: "United States",
    VE: "Venezuela",
    VN: "Vietnam",
    ZA: "South Africa"
};